### ISSUE TITLE
events api for charts - sync with external elements

### ISSUE THREAD

**Issue by aaronz8** [openhose/openhose-visualizations-sdk#31]
#### Sample use case / What I can't do easily right now
You have a chart and a list of the same data.
When hovering over or selecting an item in the *list*, the corresponding item should be highlighted in the *chart*.
When hovering over or selecting an item in the *chart*, the corresponding item should be highlighted in the *list*.

#### Proposal
I think the simplest way (from the developer perspective) is to utilize events, specifically:
- Emit `hover` event with id of what is being hovered over/selected
- Handle `select` event with id of what to select

Usage:

When hovering over list item,

    chart.emit('select', item._id) // or is it `trigger` :(...

When hovering over the chart,

    chart.on('hover', function(_id){ 
      // highlight _id in list 
    })`

**Comment by aaronz8** [comment]
To see the use case, go to Stream Settings -> Log. When you select anything in the list, it's supposed to highlight the corresponding thing in the chart. When you hover/select anything in the chart, it's supposed to highlight the corresponding thing in the list.

relevant file: https://github.com/bottlenose-inc/bottlenose/blob/e57e144a90dec15c44fefcddb9d5844c4ccefdaf/apps/web/public/plugins/dialogs/pro-stream-manager/views/stream-status/log-tab.js#L159

**Comment by Juice10** [comment]
I like this idea, we should probably return more data on trigger as just `_id` is too specific for just this usecase and we should try and keep it generic.

**Comment by aaronz8** [comment]
I've made some progress (as in, it now works enough for my purposes) in branch feature/passthrough-annotation-select. I opted to define `.select(id)` in visualization/line.js, which can pass through widget/line.js. The user has the option to set the `id` using the passed in options.annotations.data.
